name = "PyQHA"
uuid = "5a1273f0-a906-4eb0-8178-7035f457d819"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
AbInitioSoftwareBase = "df5135bc-470e-46c6-b451-292e27ca5b84"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
PyCall = "1.92"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
